// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StringResourceVisualizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "StringResourceVisualizer.a05f89b1-98f8-4b37-8f84-4fdebc44aa25";
        public const string Name = "String Resource Visualizer";
        public const string Description = @"View the text of string resources (.resx) inline when they're used in code.";
        public const string Language = "en-US";
        public const string Version = "1.17";
        public const string Author = "Matt Lacey";
        public const string Tags = "Strings, resources, localization, resx, I18N, ILocalizer";
    }
}
